version.json

[chore] update version to 2.9.7

---

version.json

[chore] update version to 2.9.8

---

version.json

update version to 2.9.9

---

version.json

[chore]version to 3.0.0

---

version.json

[chore] update iOS version to 3.0.1

---

version.json

[chore]ios update version to 3.0.2

---

version.json

[chore]iOS TempTalk version to 3.0.3

---

version.json

[chore]update version to 3.0.4

---

version.json

[chore]TempTalk iOS version to 3.0.5

---

version.json

update tempTalk version to 3.0.6

[chore]update tempTalk version to 3.0.6

---

version.json

[chore]update version to 3.0.7

---

version.json

[chore]version to 3.0.8

---

version.json

update iOS version config to 3.0.9

[chore] update iOS version config to 3.0.9

---

version.json

[chore]update version to 3.1.0

---

version.json

update iOS tt version to 3.1.1

[chore]update iOS tt version to 3.1.3

---

version.json

[chore]update version to 3.1.5

---

version.json

[chore]force update version to 3.1.6

---

version.json

update tt iOS version to 3.1.7

[chore]update tt iOS version to 3.1.7

---

version.json

[chore]update version to 3.2.1

---

version.json

[chore]update tt version to 3.2.3

---

version.json

force update iOS version to 3.2.4

[chore]force update iOS version to 3.2.4

---

version.json

[chore]update iOS version to 3.2.6

---

version.json

[chore]update version to 3.2.7

---

.well-known/apple-app-site-association

update apple-app-site-association to support /u

[feat]update apple-app-site-association

---

version.json

[chore]update iOS version to 3.2.9
